In [47]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [48]:
df_14 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2014_Sold_Player.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vinay\AppData\Local\Temp\ipykernel_18456\829886806.py:1: SyntaxWarning: invalid escape sequence '\C'
  df_14 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2014_Sold_Player.csv')

In [49]:
df_14.head()

,Unnamed: 0,Name,Price in rs,Role,TeamName,Unnamed: 5,Overseas players,Indian players
0,0,Faf Du Plessis,"4,75,00,000",Batsman,Chennai Super Kings,NaN,NaN,NaN
1,1,Dwayne Smith,"4,50,00,000",Batsman,Chennai Super Kings,NaN,Faf Du Plessis,Ashish Nehra
2,2,Brendon McCullum,"3,25,00,000",Wicket Keeper,Chennai Super Kings,NaN,Dwayne Smith,Mohit Sharma
3,3,Ashish Nehra,"2,00,00,000",Bowler,Chennai Super Kings,NaN,Brendon McCullum,Ishwar Chandra Pandey
4,4,Mohit Sharma,"2,00,00,000",Bowler,Chennai Super Kings,NaN,Ben Hilfenhaus,Mithun Manhas

In [50]:
df_14.info()

<class 'pandas.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        154 non-null    int64
 1   Name              154 non-null    str
 2   Price in rs       154 non-null    str
 3   Role              154 non-null    str
 4   TeamName          154 non-null    str
 5   Unnamed: 5        0 non-null      float64
 6   Overseas players  40 non-null     str
 7   Indian players    97 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 19.1 KB

In [51]:
df_14 =df_14.drop(['Unnamed: 0','Unnamed: 5'],axis=1)

In [52]:
overseas = df_14['Overseas players'].dropna().str.strip().str.lower().tolist()
indian = df_14['Indian players'].dropna().str.strip().str.lower().tolist()

def get_nationality(name):
    n = name.strip().lower()
    if n in overseas:
        return "Overseas"
    elif n in indian:
        return "Indian"
    return "Unknown"

df_14['nationality'] = df_14['Name'].apply(get_nationality)

In [53]:
df_14.info()

<class 'pandas.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              154 non-null    str
 1   Price in rs       154 non-null    str
 2   Role              154 non-null    str
 3   TeamName          154 non-null    str
 4   Overseas players  40 non-null     str
 5   Indian players    97 non-null     str
 6   nationality       154 non-null    str
dtypes: str(7)
memory usage: 19.0 KB

In [54]:
df_14.head()

,Name,Price in rs,Role,TeamName,Overseas players,Indian players,nationality
0,Faf Du Plessis,"4,75,00,000",Batsman,Chennai Super Kings,NaN,NaN,Overseas
1,Dwayne Smith,"4,50,00,000",Batsman,Chennai Super Kings,Faf Du Plessis,Ashish Nehra,Overseas
2,Brendon McCullum,"3,25,00,000",Wicket Keeper,Chennai Super Kings,Dwayne Smith,Mohit Sharma,Overseas
3,Ashish Nehra,"2,00,00,000",Bowler,Chennai Super Kings,Brendon McCullum,Ishwar Chandra Pandey,Indian
4,Mohit Sharma,"2,00,00,000",Bowler,Chennai Super Kings,Ben Hilfenhaus,Mithun Manhas,Indian

In [55]:
df_14 = df_14.drop(columns=['Overseas players', 'Indian players'])

In [56]:
df_14.info()

<class 'pandas.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         154 non-null    str
 1   Price in rs  154 non-null    str
 2   Role         154 non-null    str
 3   TeamName     154 non-null    str
 4   nationality  154 non-null    str
dtypes: str(5)
memory usage: 14.7 KB

In [57]:
df_14.shape

(154, 5)

In [58]:
df_14.describe()

               Name Price in rs    Role          TeamName nationality
count           154         154     154               154         154
unique          153          46       4                 8           3
top     Amit Mishra   10,00,000  Bowler  Delhi Daredevils      Indian
freq              2          26      68                23          89

In [59]:
df_14.isnull().sum()

Name           0
Price in rs    0
Role           0
TeamName       0
nationality    0
dtype: int64

In [60]:
print(df_14.shape)
print(df_14.columns.tolist())
print(df_14.head())
print(df_14.isnull().sum())
print(df_14.describe())

(154, 5)
['Name', 'Price in rs', 'Role', 'TeamName', 'nationality']
               Name  Price in rs           Role             TeamName  \
0    Faf Du Plessis  4,75,00,000        Batsman  Chennai Super Kings
1      Dwayne Smith  4,50,00,000        Batsman  Chennai Super Kings
2  Brendon McCullum  3,25,00,000  Wicket Keeper  Chennai Super Kings
3      Ashish Nehra  2,00,00,000         Bowler  Chennai Super Kings
4      Mohit Sharma  2,00,00,000         Bowler  Chennai Super Kings

  nationality
0    Overseas
1    Overseas
2    Overseas
3      Indian
4      Indian
Name           0
Price in rs    0
Role           0
TeamName       0
nationality    0
dtype: int64
               Name Price in rs    Role          TeamName nationality
count           154         154     154               154         154
unique          153          46       4                 8           3
top     Amit Mishra   10,00,000  Bowler  Delhi Daredevils      Indian
freq              2          26      68                23          89

In [63]:
df_14 = df_14.drop_duplicates(subset=['Name'])

In [77]:
# Price clean karo
df_14['price_cr'] = df_14['Price in rs'].str.replace(',', '').astype(float) / 1_00_00_000

# Unnecessary columns drop karo
df_14 = df_14.drop(columns=['Price in rs'])

# 2018

In [228]:
df_18 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2018_Sold_Player.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vinay\AppData\Local\Temp\ipykernel_18456\2050400287.py:1: SyntaxWarning: invalid escape sequence '\C'
  df_18 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2018_Sold_Player.csv')

In [229]:
df_18.head()

,Column1,Name,Price in rs,Role,TeamName,Overseas players,Indian players
0,0,Kedar Jadhav,"7,80,00,000",All-Rounder,Chennai Super Kings,NaN,NaN
1,1,Dwayne Bravo,"6,40,00,000",All-Rounder,Chennai Super Kings,Dwayne Bravo,Kedar Jadhav
2,2,Karn Sharma,"5,00,00,000",Bowler,Chennai Super Kings,Shane Watson,Karn Sharma
3,3,Shane Watson,"4,00,00,000",All-Rounder,Chennai Super Kings,Faf Du Plessis,Shardul Thakur
4,4,Shardul Narendra Thakur,"2,60,00,000",Bowler,Chennai Super Kings,Mark Wood,Ambati Rayudu

In [230]:
df_18['Name'].value_counts()

Name
Kedar Jadhav               1
Dwayne Bravo               1
Karn Sharma                1
Shane Watson               1
Shardul Narendra Thakur    1
Ambati Rayudu              1
Murali Vijay               1
Harbhajan Singh            1
Faf Du Plessis             1
Mark Wood                  1
Sam Billings               1
Imran Tahir                1
Deepak Chahar              1
Mitchell Santner           1
Lungisani Ngidi            1
Asif K M                   1
N Jagadeesan               1
Kanishk Seth               1
Monu Singh                 1
Dhruv Shorey               1
Kshitiz Sharma             1
Chaitanya Bishnoi          1
Glenn Maxwell              1
Kagiso Rabada              1
Amit Mishra                1
Shahbaz Nadeem             1
Vijay Shankar              1
Rahul Tewatia              1
Mohammad Shami             1
Gautam Gambhir             1
Trent Boult                1
Colin Munro                1
Daniel Christian           1
Jason Roy                  1
Naman Ojha                 1
Prithvi Shaw               1
Gurkeerat Singh Mann       1
Avesh Khan                 1
Abhishek Sharma            1
Jayant Yadav               1
Harshal Patel              1
Manjot Kalra               1
Sandeep Lamichhane         1
Sayan Ghosh                1
KL Rahul                   1
Ravichandran Ashwin        1
Andrew Tye                 1
Aaron Finch                1
Marcus Stoinis             1
Karun Nair                 1
Mujeeb Zadran              1
Ankit Singh Rajpoot        1
David Miller               1
Mohit Sharma               1
Barinder Singh Sran        1
Yuvraj Singh               1
Christopher Gayle          1
Ben Dwarshuis              1
Akshdeep Nath              1
Manoj Tiwary               1
Mayank Agarwal             1
Manzoor Dar                1
Pardeep Sahu               1
Mayank Dagar               1
Chris Lynn                 1
Mitchell Starc             1
Dinesh Karthik             1
Robin Uthappa              1
Kuldeep Singh Yadav        1
Piyush Chawla              1
Nitish Rana                1
Kamlesh Nagarkoti          1
Shivam Mavi                1
Mitchell Johnson           1
Shubman Gill               1
Ranganath Vinay Kumar      1
Rinku Singh                1
Cameron Delport            1
Javon Searless             1
Apoorv Vijay Wankhade      1
Ishank Jaggi               1
Krunal Pandya              1
Ishan Kishan               1
Kieron Pollard             1
Pat Cummins                1
Evin Lewis                 1
Suryakumar Yadav           1
Ben Cutting                1
Mustafizur Rahman          1
Rahul Chahar               1
Pradeep Sangwan            1
Jason Behrendorff          1
Jean-Paul Duminy           1
Saurabh Tiwary             1
Tajinder Dhillon           1
Akila Dhananjaya           1
Nidheesh M D Dinesan       1
Aditya Tare                1
Siddhesh Dinesh Lad        1
Mayank Markande            1
Sharad Lumba               1
Anukul Roy                 1
Mohsin Khan                1
Benjamin Stokes            1
Jaydev Unadkat             1
Sanju Samson               1
Jofra Archer               1
Krishnappa Gowtham         1
Jos Buttler                1
Ajinkya Rahane             1
Darcy Short                1
Rahul Tripathi             1
Dhawal Kulkarni            1
Zahir Khan Pakteen         1
Ben Laughlin               1
Stuart Binny               1
Dushmantha Chameera        1
Anureet Singh              1
Aryaman Vikram Birla       1
Midhun S                   1
Shreyas Gopal              1
Prashant Chopra            1
Jatin Saxena               1
Ankit Sharma               1
Mahipal Lomror             1
Chris Woakes               1
Yuzvendra Singh Chahal     1
Umesh Yadav                1
Brendon McCullum           1
M.S. Washington Sundar     1
Navdeep Saini              1
Quinton De Kock            1
Mohammed Siraj             1
Nathan Coulter-Nile        1
Colin De Grandhomme        1
M. Ashwin                  1
Parthiv Patel              1
Moeen Ali                  1
Mandeep Singh              1
Manan Vohra                1
Pawan Negi                 1
Tim Southee                1
Kulwant Khejroliya         1
Aniket Choudhary           1
Pavan Deshpande            1
Anirudha Ashok Joshi       1
Manish Pandey              1
Rashid Khan Arman          1
Shikhar Dhawan             1
Wriddhiman Saha            1
Siddarth Kaul              1
Deepak Hooda               1
Syed Khaleel Ahmed         1
Sandeep Sharma             1
Kane Williamson            1
Carlos Brathwaite          1
Shakib Al Hasan            1
Yusuf Pathan               1
Shreevats Goswami          1
Mohammad Nabi              1
Chris Jordan               1
Basil Thampi               1
Billy Stanlake             1
T Natarajan                1
Sachin Baby                1
Bipul Sharma               1
Syed Mehdi Hasan           1
Ricky Bhui                 1
Tanmay Agarwal             1
Name: count, dtype: int64

In [231]:
overseas = df_18['Overseas players'].dropna().str.strip().str.lower().tolist()
indian = df_18['Indian players'].dropna().str.strip().str.lower().tolist()

def get_nationality(Name):
    n = Name.strip().lower()
    if n in overseas:
        return "Overseas"
    elif n in indian:
        return "Indian"
    return "Unknown"

df_18['nationality'] = df_18['Name'].apply(get_nationality)

In [232]:
df_18=df_18.drop(columns=['Column1','Overseas players',	'Indian players'])

In [233]:
df_18['Name'].value_counts()

Name
Kedar Jadhav               1
Dwayne Bravo               1
Karn Sharma                1
Shane Watson               1
Shardul Narendra Thakur    1
Ambati Rayudu              1
Murali Vijay               1
Harbhajan Singh            1
Faf Du Plessis             1
Mark Wood                  1
Sam Billings               1
Imran Tahir                1
Deepak Chahar              1
Mitchell Santner           1
Lungisani Ngidi            1
Asif K M                   1
N Jagadeesan               1
Kanishk Seth               1
Monu Singh                 1
Dhruv Shorey               1
Kshitiz Sharma             1
Chaitanya Bishnoi          1
Glenn Maxwell              1
Kagiso Rabada              1
Amit Mishra                1
Shahbaz Nadeem             1
Vijay Shankar              1
Rahul Tewatia              1
Mohammad Shami             1
Gautam Gambhir             1
Trent Boult                1
Colin Munro                1
Daniel Christian           1
Jason Roy                  1
Naman Ojha                 1
Prithvi Shaw               1
Gurkeerat Singh Mann       1
Avesh Khan                 1
Abhishek Sharma            1
Jayant Yadav               1
Harshal Patel              1
Manjot Kalra               1
Sandeep Lamichhane         1
Sayan Ghosh                1
KL Rahul                   1
Ravichandran Ashwin        1
Andrew Tye                 1
Aaron Finch                1
Marcus Stoinis             1
Karun Nair                 1
Mujeeb Zadran              1
Ankit Singh Rajpoot        1
David Miller               1
Mohit Sharma               1
Barinder Singh Sran        1
Yuvraj Singh               1
Christopher Gayle          1
Ben Dwarshuis              1
Akshdeep Nath              1
Manoj Tiwary               1
Mayank Agarwal             1
Manzoor Dar                1
Pardeep Sahu               1
Mayank Dagar               1
Chris Lynn                 1
Mitchell Starc             1
Dinesh Karthik             1
Robin Uthappa              1
Kuldeep Singh Yadav        1
Piyush Chawla              1
Nitish Rana                1
Kamlesh Nagarkoti          1
Shivam Mavi                1
Mitchell Johnson           1
Shubman Gill               1
Ranganath Vinay Kumar      1
Rinku Singh                1
Cameron Delport            1
Javon Searless             1
Apoorv Vijay Wankhade      1
Ishank Jaggi               1
Krunal Pandya              1
Ishan Kishan               1
Kieron Pollard             1
Pat Cummins                1
Evin Lewis                 1
Suryakumar Yadav           1
Ben Cutting                1
Mustafizur Rahman          1
Rahul Chahar               1
Pradeep Sangwan            1
Jason Behrendorff          1
Jean-Paul Duminy           1
Saurabh Tiwary             1
Tajinder Dhillon           1
Akila Dhananjaya           1
Nidheesh M D Dinesan       1
Aditya Tare                1
Siddhesh Dinesh Lad        1
Mayank Markande            1
Sharad Lumba               1
Anukul Roy                 1
Mohsin Khan                1
Benjamin Stokes            1
Jaydev Unadkat             1
Sanju Samson               1
Jofra Archer               1
Krishnappa Gowtham         1
Jos Buttler                1
Ajinkya Rahane             1
Darcy Short                1
Rahul Tripathi             1
Dhawal Kulkarni            1
Zahir Khan Pakteen         1
Ben Laughlin               1
Stuart Binny               1
Dushmantha Chameera        1
Anureet Singh              1
Aryaman Vikram Birla       1
Midhun S                   1
Shreyas Gopal              1
Prashant Chopra            1
Jatin Saxena               1
Ankit Sharma               1
Mahipal Lomror             1
Chris Woakes               1
Yuzvendra Singh Chahal     1
Umesh Yadav                1
Brendon McCullum           1
M.S. Washington Sundar     1
Navdeep Saini              1
Quinton De Kock            1
Mohammed Siraj             1
Nathan Coulter-Nile        1
Colin De Grandhomme        1
M. Ashwin                  1
Parthiv Patel              1
Moeen Ali                  1
Mandeep Singh              1
Manan Vohra                1
Pawan Negi                 1
Tim Southee                1
Kulwant Khejroliya         1
Aniket Choudhary           1
Pavan Deshpande            1
Anirudha Ashok Joshi       1
Manish Pandey              1
Rashid Khan Arman          1
Shikhar Dhawan             1
Wriddhiman Saha            1
Siddarth Kaul              1
Deepak Hooda               1
Syed Khaleel Ahmed         1
Sandeep Sharma             1
Kane Williamson            1
Carlos Brathwaite          1
Shakib Al Hasan            1
Yusuf Pathan               1
Shreevats Goswami          1
Mohammad Nabi              1
Chris Jordan               1
Basil Thampi               1
Billy Stanlake             1
T Natarajan                1
Sachin Baby                1
Bipul Sharma               1
Syed Mehdi Hasan           1
Ricky Bhui                 1
Tanmay Agarwal             1
Name: count, dtype: int64

In [234]:
df_18.head()
df_18.duplicated()
df_18.info()
df_18.describe()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         169 non-null    str
 1   Price in rs  169 non-null    str
 2   Role         169 non-null    str
 3   TeamName     169 non-null    str
 4   nationality  169 non-null    str
dtypes: str(5)
memory usage: 16.4 KB

,Name,Price in rs,Role,TeamName,nationality
count,169,169,169,169,169
unique,169,53,4,8,2
top,Kedar Jadhav,"20,00,000",All-Rounder,Sunrisers Hyderabad,Indian
freq,1,35,61,23,105

In [235]:
# Price clean karo
df_18['price_cr'] = df_18['Price in rs'].str.replace(',', '').astype(float) / 1_00_00_000

# Unnecessary columns drop karo
df_18 = df_18.drop(columns=['Price in rs'])

In [236]:
print(df_18['nationality'].value_counts())

nationality
Indian      105
Overseas     64
Name: count, dtype: int64

In [237]:
print(df_18[df_18['nationality'] == 'Unknown']['Name'].tolist())

[]

In [238]:
df_18.head()

,Name,Role,TeamName,nationality,price_cr
0,Kedar Jadhav,All-Rounder,Chennai Super Kings,Indian,7.8
1,Dwayne Bravo,All-Rounder,Chennai Super Kings,Overseas,6.4
2,Karn Sharma,Bowler,Chennai Super Kings,Indian,5.0
3,Shane Watson,All-Rounder,Chennai Super Kings,Overseas,4.0
4,Shardul Narendra Thakur,Bowler,Chennai Super Kings,Indian,2.6

In [239]:
df_18['Name'].duplicated().value_counts()

Name
False    169
Name: count, dtype: int64

# 2022

In [241]:
df_22 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2022_Sold_Player.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vinay\AppData\Local\Temp\ipykernel_18456\1468440911.py:1: SyntaxWarning: invalid escape sequence '\C'
  df_22 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2022_Sold_Player.csv')

In [243]:
df_22.head()

,Unnamed: 0,Name,Nationality,Price in rs,Role,TeamName
0,0,Robin Uthappa,Indian,"2,00,00,000",Batsman,Chennai Super Kings
1,1,Dwayne Bravo,Overseas,"4,40,00,000",All-Rounder,Chennai Super Kings
2,2,Ambati Rayudu,Indian,"6,75,00,000",Wicket Keeper,Chennai Super Kings
3,3,Deepak Chahar,Indian,"14,00,00,000",Bowler,Chennai Super Kings
4,4,C.Hari Nishaanth,Indian,"20,00,000",Batsman,Chennai Super Kings

In [250]:
df_22.info()
df_22.describe()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   204 non-null    int64
 1   Name         204 non-null    str
 2   nationality  204 non-null    str
 3   Price in rs  204 non-null    str
 4   Role         204 non-null    str
 5   TeamName     204 non-null    str
 6   price_cr     204 non-null    float64
dtypes: float64(1), int64(1), str(5)
memory usage: 23.5 KB

       Unnamed: 0    price_cr
count  204.000000  204.000000
mean   101.500000    2.704412
std     59.033889    3.323203
min      0.000000    0.200000
25%     50.750000    0.200000
50%    101.500000    1.050000
75%    152.250000    4.000000
max    203.000000   15.250000

In [247]:
df_22.rename(columns={'Nationality':'nationality'},inplace=True)

In [249]:
df_22['price_cr'] = df_22['Price in rs'].str.replace(',', '').astype(float) / 1_00_00_000

In [253]:
df_22.drop(columns=['Unnamed: 0','Price in rs'],inplace=True)

In [254]:
df_22.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         204 non-null    str
 1   nationality  204 non-null    str
 2   Role         204 non-null    str
 3   TeamName     204 non-null    str
 4   price_cr     204 non-null    float64
dtypes: float64(1), str(4)
memory usage: 18.1 KB

# 2025

In [264]:
df_25 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2025_Sold_Player.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vinay\AppData\Local\Temp\ipykernel_18456\2024548321.py:1: SyntaxWarning: invalid escape sequence '\C'
  df_25 = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\Auction Data\IPL_Auction_2025_Sold_Player.csv')

In [268]:
df_25.info()

<class 'pandas.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               182 non-null    str
 1   Nationality        182 non-null    str
 2   Winning Bid in Rs  182 non-null    str
 3   TeamName           182 non-null    str
 4   price_cr           182 non-null    float64
dtypes: float64(1), str(4)
memory usage: 16.1 KB

In [ ]:
df_25.drop(columns=['BasePrices in Rs','Capped/UnCapped'],inplace=True)

KeyError: "['BasePrices in Rs', 'Capped/UnCapped'] not found in axis"

In [267]:
df_25['price_cr'] = df_25['Winning Bid in Rs'].str.replace(',','').astype(float)/10000000

In [271]:
df_25.drop('Winning Bid in Rs',axis=1,inplace=True)

In [277]:
df_25.info()
df_14.info()
df_18.info()
df_22.info()

<class 'pandas.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         182 non-null    str
 1   Nationality  182 non-null    str
 2   TeamName     182 non-null    str
 3   price_cr     182 non-null    float64
dtypes: float64(1), str(3)
memory usage: 12.9 KB
<class 'pandas.DataFrame'>
Index: 153 entries, 0 to 153
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         153 non-null    str
 1   Role         153 non-null    str
 2   TeamName     153 non-null    str
 3   nationality  153 non-null    str
 4   price_cr     153 non-null    float64
dtypes: float64(1), str(4)
memory usage: 14.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         169 non-null    str
 1   Role         169 non-null    str
 2   TeamName     169 non-null    str
 3   nationality  169 non-null    str
 4   price_cr     169 non-null    float64
dtypes: float64(1), str(4)
memory usage: 14.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         204 non-null    str
 1   nationality  204 non-null    str
 2   Role         204 non-null    str
 3   TeamName     204 non-null    str
 4   price_cr     204 non-null    float64
dtypes: float64(1), str(4)
memory usage: 18.1 KB

In [278]:
# 2022 - rename column
df_22 = df_22.rename(columns={'Nationality': 'nationality'})

df_25 = df_25.rename(columns={'Nationality': 'nationality'})

In [289]:
df_14['year'] = 2014
df_18['year'] = 2018
df_22['year'] = 2022
df_25['year'] = 2025

# Concat all the 4 tables

In [290]:
final_auction = pd.concat([df_14,df_18,df_22,df_25],ignore_index=True)

In [291]:
final_auction.info()

<class 'pandas.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         708 non-null    str
 1   Role         526 non-null    str
 2   TeamName     708 non-null    str
 3   nationality  708 non-null    str
 4   price_cr     708 non-null    float64
 5   year         708 non-null    int64
dtypes: float64(1), int64(1), str(4)
memory usage: 65.5 KB

In [292]:
final_auction.drop(columns=['Role'],inplace=True)

In [293]:
print(final_auction['nationality'].value_counts())
print(final_auction['TeamName'].unique())

nationality
Indian       308
Overseas     171
Indian       137
Overseas      67
Unknown       25
Name: count, dtype: int64
<ArrowStringArray>
[         'Chennai Super Kings',             'Delhi Daredevils',
              'Kings XI Punjab',        'Kolkata Knight Riders',
               'Mumbai Indians',             'Rajasthan Royals',
 ' Royal Challengers Bengaluru',         ' Sunrisers Hyderabad',
         ' Chennai Super Kings',       ' Kolkata Knight Riders',
              ' Mumbai Indians',            ' Rajasthan Royals',
              ' Delhi Capitals',              ' Gujarat Titans',
        ' Lucknow Super Giants',                ' Punjab Kings',
 ' Royal Challengers Bangalore']
Length: 17, dtype: str

In [294]:
# Nationality fix
final_auction['nationality'] = final_auction['nationality'].str.strip().str.title()

# TeamName fix - extra spaces hatao
final_auction['TeamName'] = final_auction['TeamName'].str.strip()

# Team names standardize karo
team_map = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bengaluru': 'Royal Challengers Bangalore'
}
final_auction['TeamName'] = final_auction['TeamName'].replace(team_map)

# Check
print(final_auction['nationality'].value_counts())
print(final_auction['TeamName'].unique())

nationality
Indian      445
Overseas    238
Unknown      25
Name: count, dtype: int64
<ArrowStringArray>
[        'Chennai Super Kings',              'Delhi Capitals',
                'Punjab Kings',       'Kolkata Knight Riders',
              'Mumbai Indians',            'Rajasthan Royals',
 'Royal Challengers Bangalore',         'Sunrisers Hyderabad',
              'Gujarat Titans',        'Lucknow Super Giants']
Length: 10, dtype: str

In [295]:
print(final_auction[final_auction['nationality'] == 'Unknown']['Name'].tolist())

['Kevin Pietersen', 'Virender Sehwag', 'Rishi Dhawan', 'Wriddhiman Saha', 'Shaun Marsh', 'Cheteshwar Pujara', 'Beuran Hendricks', 'Lakshmipathy Balaji', 'Thisara Perera', 'Mandeep Hardev Singh', 'Akshar Rajesh Patel', 'Shardul Narendra Thakur', 'Shakib Al Hasan', 'Morne Morkel', 'Ranganath Vinay Kumar', 'Chris Lynn', 'Patrick Cummins', 'Kuldeep Singh Yadav', 'Sayan Sekhar Mandal', 'Zaheer Khan', 'Ben Dunk', 'Apoorv Vijay Wankhade', 'Kevon Cooper', 'Ankit Nagendra Sharma', 'Yuzvendra Singh Chahal']

In [296]:
manual_map = {
    'kevin pietersen': 'Overseas',
    'shaun marsh': 'Overseas',
    'beuran hendricks': 'Overseas',
    'thisara perera': 'Overseas',
    'shakib al hasan': 'Overseas',
    'morne morkel': 'Overseas',
    'chris lynn': 'Overseas',
    'patrick cummins': 'Overseas',
    'ben dunk': 'Overseas',
    'kevon cooper': 'Overseas',
    'virender sehwag': 'Indian',
    'rishi dhawan': 'Indian',
    'wriddhiman saha': 'Indian',
    'cheteshwar pujara': 'Indian',
    'lakshmipathy balaji': 'Indian',
    'mandeep hardev singh': 'Indian',
    'akshar rajesh patel': 'Indian',
    'shardul narendra thakur': 'Indian',
    'ranganath vinay kumar': 'Indian',
    'kuldeep singh yadav': 'Indian',
    'sayan sekhar mandal': 'Indian',
    'zaheer khan': 'Indian',
    'apoorv vijay wankhade': 'Indian',
    'ankit nagendra sharma': 'Indian',
    'yuzvendra singh chahal': 'Indian'
}

final_auction['nationality'] = final_auction.apply(
    lambda row: manual_map.get(row['Name'].strip().lower(), row['nationality']),
    axis=1
)

print(final_auction['nationality'].value_counts())

nationality
Indian      463
Overseas    245
Name: count, dtype: int64

In [297]:
final_auction.to_csv('auction_players_clean.csv',index=False)

# Retained players

In [306]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [322]:
ret_14 = pd.read_excel('F:/CODING/ipl project/drive-download-20260415T150344Z-3-001/Auction Data/2014retain.xlsx')
ret_18 = pd.read_excel('F:/CODING/ipl project/drive-download-20260415T150344Z-3-001/Auction Data/2018retaindata.xlsx')
ret_22 = pd.read_excel('F:/CODING/ipl project/drive-download-20260415T150344Z-3-001/Auction Data/retain2022.xlsx')
ret_25 = pd.read_excel('F:/CODING/ipl project/drive-download-20260415T150344Z-3-001/Auction Data/2025retaindata.xlsx')

In [323]:
ret_25 = ret_25.drop('Nationality', axis = 1)

In [330]:
ret_14.rename(columns={'Nationality':'nationality'},inplace=True)
ret_22.rename(columns={'Nationality':'nationality'},inplace=True)

In [343]:
print(ret_14.columns.tolist())
print(ret_18.columns.tolist())
print(ret_22.columns.tolist())
print(ret_25.columns.tolist())

['Name', 'TeamName', 'nationality', 'price_cr', 'year']
['Name', 'TeamName', 'nationality', 'price_cr', 'year']
['Name', 'TeamName', 'nationality', 'price_cr', 'year']
['Name', 'TeamName', 'nationality', 'price_cr', 'year']

In [328]:
ret_25.head()

  Team               Player  Price (Cr) nationality
0  CSK      Ruturaj Gaikwad        18.0      Indian
1  CSK      Ravindra Jadeja        18.0      Indian
2  CSK  Matheesha Pathirana        13.0    Overseas
3  CSK          Shivam Dube        12.0      Indian
4  CSK             MS Dhoni         4.0      Indian

In [334]:
ret_14=ret_14[['Player','Team','nationality','Estimated_Price_Cr']]
ret_18=ret_18[['Player','Team','nationality','Price']]
ret_22=ret_22[['Player','Team','nationality','Price']]
ret_25=ret_25[['Player','Team','nationality','Price (Cr)']]

In [339]:
cols = ['Name', 'TeamName', 'nationality', 'price_cr']

ret_14 = ret_14[['Player','Team','nationality','Estimated_Price_Cr']]
ret_14.columns = cols

ret_18 = ret_18[['Player','Team','nationality','Price']]
ret_18.columns = cols

ret_22 = ret_22[['Player','Team','nationality','Price']]
ret_22.columns = cols

ret_25 = ret_25[['Player','Team','nationality','Price (Cr)']]
ret_25.columns = cols

In [342]:
ret_14['year'] = ret_14['year']= '2014'
ret_18['year'] = ret_18['year']= '2018'
ret_22['year'] = ret_22['year']= '2022'
ret_25['year'] = ret_25['year']= '2025'

In [341]:
ret_14.head()

              Name TeamName nationality  price_cr  year
0         MS Dhoni      CSK      Indian      12.0  2014
1     Suresh Raina      CSK      Indian      10.0  2014
2  Ravindra Jadeja      CSK      Indian       9.0  2014
3         R Ashwin      CSK      Indian       7.0  2014
4     Dwayne Bravo      CSK    Overseas       8.0  2014

In [345]:
retain_merge_df=pd.concat([ret_14,ret_18,ret_22,ret_25])

In [351]:
retain_merge_df.info()

<class 'pandas.DataFrame'>
Index: 115 entries, 0 to 54
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         115 non-null    str
 1   TeamName     115 non-null    str
 2   nationality  115 non-null    str
 3   price_cr     115 non-null    float64
 4   year         115 non-null    str
dtypes: float64(1), str(4)
memory usage: 8.4 KB

In [348]:
retain_merge_df.to_csv('retain_clean.csv',index=False)

In [350]:
retain_merge_df = retain_merge_df.dropna()

In [366]:
final_merge = pd.concat([retain_merge_df,final_auction])

In [367]:
final_merge.head()

              Name TeamName nationality  price_cr  year
0         MS Dhoni      CSK      Indian      12.0  2014
1     Suresh Raina      CSK      Indian      10.0  2014
2  Ravindra Jadeja      CSK      Indian       9.0  2014
3         R Ashwin      CSK      Indian       7.0  2014
4     Dwayne Bravo      CSK    Overseas       8.0  2014

In [368]:
final_merge.info()

<class 'pandas.DataFrame'>
Index: 823 entries, 0 to 707
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         823 non-null    str
 1   TeamName     823 non-null    str
 2   nationality  823 non-null    str
 3   price_cr     823 non-null    float64
 4   year         823 non-null    object
dtypes: float64(1), object(1), str(3)
memory usage: 67.6+ KB

In [369]:
team_map = {
    'CSK': 'Chennai Super Kings',
    'MI': 'Mumbai Indians',
    'RCB': 'Royal Challengers Bangalore',
    'KKR': 'Kolkata Knight Riders',
    'SRH': 'Sunrisers Hyderabad',
    'RR': 'Rajasthan Royals',
    'KXIP': 'Punjab Kings',
    'PBKS': 'Punjab Kings',
    'DD': 'Delhi Capitals',
    'DC': 'Delhi Capitals',
    'GT': 'Gujarat Titans',
    'LSG': 'Lucknow Super Giants'
}

final_merge['TeamName'] = final_merge['TeamName'].map(team_map).fillna(final_merge['TeamName'])

In [370]:
final_merge.info()

<class 'pandas.DataFrame'>
Index: 823 entries, 0 to 707
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         823 non-null    str
 1   TeamName     823 non-null    str
 2   nationality  823 non-null    str
 3   price_cr     823 non-null    float64
 4   year         823 non-null    object
dtypes: float64(1), object(1), str(3)
memory usage: 69.3+ KB

In [371]:
final_merge['TeamName'].value_counts()

TeamName
Chennai Super Kings            95
Delhi Capitals                 95
Punjab Kings                   94
Mumbai Indians                 94
Rajasthan Royals               92
Sunrisers Hyderabad            91
Royal Challengers Bangalore    89
Kolkata Knight Riders          86
Gujarat Titans                 45
Lucknow Super Giants           42
Name: count, dtype: int64

In [372]:
final_merge.to_csv('all_players_salary_final.csv',index = False)